spring:
  application:
    name: api-server

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret1234}

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  security:
    oauth2:
      jwt:
        access-expired: 1800000
        refresh-expired: 2592000000
        secret:
          key: ${SECRET_KEY:secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret1234secret}

  mail:
    host: smtp.email.ap-chuncheon-1.oci.oraclecloud.com
    username: ${OCI_SMTP_USERNAME}
    password: ${OCI_SMTP_PASSWORD}

  oci:
    bucket: ${OCI_BUCKET_NAME}
    namespace: ${OCI_NAMESPACE}
    private-key: ${OCI_PRIVATE_KEY}
    tenant-id: ${OCI_TENANT_ID}
    user-id: ${OCI_USER_ID}
    fingerprint: ${OCI_FINGERPRINT}