apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app.kubernetes.io/name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: api-server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hbnation-config
      imagePullSecrets:
        - name: docker-registry