name: Build my Server
on:
  push:
    branches: [main]

env:
  app-name: "api-server"

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest

    outputs:
      app-name: ${{ env.app-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build
        run: mvn -B package -DskipTests=true --file pom.xml

      - name: Config Docker
        uses: docker/login-action@v3
        with:
          registry: yny.ocir.io
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}

      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.OCI_REGISTRY_URL }}/${{ env.app-name }}:${{ github.sha }}